import java.util.ArrayList;
import java.util.Arrays;
import java.util.InputMismatchException;
import java.util.Random;
import java.util.Scanner;

/**
 * This class implements the game Guessing Game which allows user to guess the answer with 3 tries.
 * @author Angelica Dela Cruz & Ben Duke
 *
 */

public class GuessingGame {
	/**
	 * The number of tries 
	 */
	private int tries = 0;
	
	/**
	 * A boolean value which represents win (true) and loss (false)
	 */
	private boolean win = false;
	
	/**
	 * The status of the game, whether the answer is correct or incorrect
	 */
	private String gameStatus;
	
	/**
	 * Answer generated by the Computer
	 */
	private int answer;
	
	/**
	 * The guess of the user
	 */
	private int guess;
	
	/**
	 * This function determines if the Computer or the Player won.
	 */
	public void whoWin() {
		if(guess == answer) {
			win = true;
			gameStatus = "correct";
				
		} else if(guess != answer) {
			gameStatus = "incorrect";
		}
		System.out.println("Your answer is " + gameStatus + ".");
		tries += 1;	
		
		if(win == true) {
			System.out.println("You won. Congratulations!");
		} else if((win == false) && (tries >= 3)) {
			System.out.println("You lost. Better luck next time!");
		}
	}
	
	/**
	 * This function initializes the user input and checks if the input is valid.
	 * If not, it initializes again.
	 */
	public void userInput() {
		ArrayList<Integer> possibles = new ArrayList<Integer>(Arrays.asList(1, 2, 3, 4, 5, 6, 7, 8, 9, 10));
		Scanner scanner = new Scanner(System.in);
		System.out.println("Enter an integer between 1 to 10:");
		while(!scanner.hasNextInt()) {
			System.out.println("---------------------------------");
			System.out.println("Invalid input.");
			System.out.println("Enter an integer between 1 to 10:");
			scanner.next();
		} guess = scanner.nextInt();
		if(possibles.contains(guess)) {
			whoWin();
		} else {
			System.out.println("---------------------------------");
			System.out.println("Integer is out of range.");
			userInput();
		}
	}
	
	/**
	 * A function that starts the game of Guessing Game and lets the user
	 * input the guessed answer.
	 */
	public void PlayGame() {
		Random number = new Random();
		answer = number.nextInt(11);
		
		while ((tries < 3) && (win == false)) {
			userInput();
		}
	}

//	public static void main(String[] args) {
//		GuessingGame g1 = new GuessingGame();
//		g1.PlayGame();
//		// TODO Auto-generated method stub
//
//	}

}
