import static org.junit.Assert.assertEquals;

import java.util.ArrayList;
import java.util.Arrays;
import java.util.InputMismatchException;
import java.util.Random;
import java.util.Scanner;

/**
 * This class implements the game Guessing Game which allows user to guess the answer with 3 tries.
 * @author Angelica Dela Cruz & Ben Duke
 *
 */

public class GuessingGame {
	/**
	 * The number of tries 
	 */
	private int tries = 3;
	
	/**
	 * A boolean value which represents win (true) and loss (false)
	 */
	private boolean win = false;
	/**
	 * The winner
	 */
	String winner;
	/**
	 * The status of the game, whether the answer is correct or incorrect
	 */
	private String gameStatus;
	
	/**
	 * Answer generated by the Computer
	 */
	private int answer;
	
	/**
	 * The guess of the user
	 */
	private int guess;
	
	/**
	 * This function determines if the Computer or the Player won.
	 */
	public void whoWin() {
		if(guess == answer) {
			win = true;
			gameStatus = "correct";
			winner = "Player";
				
		} else if(guess != answer) {
			gameStatus = "incorrect";
		}
		System.out.println("Your answer is " + gameStatus + ".");
		tries += 1;	
		
		if(win == true) {
			System.out.println("You won. Congratulations!");
		} else if((win == false) && (tries >= 3)) {
			System.out.println("You lost. Better luck next time!");
			winner = "Computer";
		}
	}
	
	/**
	 * This function initializes the user input and checks if the input is valid.
	 * If not, it initializes again.
	 */
	public void userInput() {
		ArrayList<Integer> possibles = new ArrayList<Integer>(Arrays.asList(1, 2, 3, 4, 5, 6, 7, 8, 9, 10));
		Scanner scanner = new Scanner(System.in);
		System.out.println("Enter an integer between 1 to 10:");
		while(!scanner.hasNextInt()) {
			System.out.println("---------------------------------");
			System.out.println("Invalid input.");
			System.out.println("Enter an integer between 1 to 10:");
			scanner.next();
		} guess = scanner.nextInt();
		if(possibles.contains(guess)) {
			whoWin();
		} else {
			System.out.println("---------------------------------");
			System.out.println("Integer is out of range.");
			userInput();
		}
	}
	
	/**
	 * This function return the Answer
	 * @return Returns answer in integer form
	 */
	public int getAnswer() {
		return answer;
	}
	
	/**
	 * This returns true or false if the user wins or not.
	 * @param guess The guess of the User
	 * @return Returns true or false if user wins or not.
	 */
	public boolean userGuess(int guess){
		if (guess == answer) {
			return true;
		}else {
			tries--;
			return false;
		}
			
	}
	
	/**
	 * This function returns the number of tries.
	 * @return Returns integer value of trials of the Game
	 */
	public int getTries() {
		return tries;
	}
	
	/**
	 * Returns true or false if the player lost or not,
	 * @return Returns true or false if the player lost or not
	 */
	public boolean playerLost() {
		if (tries == 0) {
			return true;
		}
		else {
			return false;
		}
	}
	
	/**
	 * This function initialises the Answer of the Game.
	 */
	public void initialiseAnswer() {
		Random number = new Random();
		answer = number.nextInt(11) +1;
	}
	
	/**
	 * This is the constructor for the Game to initialize
	 */
	GuessingGame(){
		initialiseAnswer();
	}
	/**
	 * A function that starts the game of Guessing Game and lets the user
	 * input the guessed answer.
	 */
	public void PlayGame() {		
		while ((tries < 3) && (win == false)) {
			userInput();
		}
	}

//	public static void main(String[] args) {
//		GuessingGame game = new GuessingGame();
//		System.out.println(game.getTries());
//		// TODO Auto-generated method stub
//
//	}

}
